GET http://localhost:3000/test

GET http://localhost:3000/health-checkup?username=sony&password=pass&kidneyId=1 HTTP/1.1


POST http://localhost:3000/health-checkup HTTP/1.1
Content-Type: application/json

{
  "username": "sony",
  "password": "pass",
  "kidneyId": 1
}